Args=--initialize-at-run-time=com.github.jknack.handlebars.internal.Files \
     --initialize-at-run-time=com.github.jknack.handlebars.helper.DefaultHelperRegistry \
     -H:IncludeResources=helpers.nashorn.js \
     -H:IncludeResources=handlebars-v4.7.7.js \
     -H:IncludeResources=com/github/jknack/handlebars/.* \
     -H:ReflectionConfigurationResources=${.}/reflect-config.json \
     -H:ResourceConfigurationResources=${.}/resource-config.json
